#!/bin/bash
set -e
case "$1" in
    remove|upgrade|deconfigure)
        echo "Preparing to remove dbusermgr-suite..."
    ;;
    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument `$1'" >&2
        exit 1
    ;;
esac
exit 0
